package com.sambhav.tws.utils

import android.os.Environment


var BASE_DIRECTORY_PATH =
    Environment.getExternalStorageDirectory().toString() + "/LearnomaLive"
var BASE_DOC_RECEIVE_PATH = BASE_DIRECTORY_PATH + "/Media/Documents/"

const val DUMMY_URL = "https://upload.wikimedia.org/wikipedia/commons/7/7e/Circle-icons-profile.svg"
const val Live = "Live Classes"
const val Video = "Video Library"
const val Notes = "Notes &\nResources"
const val Doubt_Room = "Doubt Room"
const val Test_Series = "Test Series"

const val TODAY_EVENT = "Today's Events"
const val UPCOMIG_EVENT = "Upcoming Events"
const val PAST_EVENT = "Past Events"
const val OPEN_MEDIA_PICKER = 1
const val DocumnetRequest = 1001
const val KOTA_FACTORY_SCHOOL_ID = "12"
const val TEMP_FILE = "temp."


const val EXTRA_KEY_ACTION = "Action"
const val EXTRA_KEY_IS_START = "isStart"
const val EXTRA_KEY_SUBJECT_ID = "EXTRA_KEY_SUBJECT_ID"
const val EXTRA_KEY_SUBJECT_NAME = "EXTRA_KEY_SUBJECT_NAME"
const val EXTRA_KEY_CHAPTER_ID = "EXTRA_KEY_CHAPTER_ID"
const val EXTRA_KEY_VIDEO_ID = "EXTRA_KEY_VIDEO_ID"
const val EXTRA_KEY_CHAPTER_NAME = "EXTRA_KEY_CHAPTER_NAME"
const val EXTRA_KEY_URL = "EXTRA_KEY_URL"
const val EXTRA_KEY_TITLE = "EXTRA_KEY_TITLE"
const val EXTRA_KEY_VIDEO_TYPE = "EXTRA_KEY_VIDEO_TYPE"
const val EXTRA_KEY_EXTENSION = "EXTRA_KEY_EXTENSION"
const val EXTRA_KEY_TEST_ID = "EXTRA_KEY_TEST_ID"
const val EXTRA_KEY_EXAM_DATA = "EXTRA_KEY_EXAM_DATA"
const val EXTRA_KEY_RESULT_DATA = "EXTRA_KEY_RESULT_DATA"
const val EXTRA_KEY_FILE_PATH = "EXTRA_KEY_FILE_PATH"

const val ACTION_WAIT = "Wait"
const val ACTION_ADD = "Add"
const val ACTION_VIEW = "View"
const val ACTION_START = "Start"
const val ACTION_EDIT = "Edit"
const val ACTION_DELETE = "Delete"
const val ACTION_DOWNLOAD = "Download"

const val API_KEY_ID = "id"
const val API_KE_SCHOOL_ID = "school_id"
const val API_KE_TEACHER_ID = "teacher_id"
const val API_KEY_STUDENT_ID = "student_id"
const val API_KEY_GRADE_ID = "grade_id"
const val API_KEY_TEST_ID = "test_id"
const val API_KEY_SUBJECT_ID = "subject_id"
const val API_KEY_STREAM_ID = "stream_id"
const val API_KEY_CHAPTER_ID = "chapter_id"
const val API_KEY_LIBRARY_ID = "document_library_id"
const val API_KEY_CHAPTER_TITLE = "chapter_title"
const val API_KEY_NAME = "name"
const val API_KEY_FIRST_NAME = "first_name"
const val API_KEY_LAST_NAME = "last_name"
const val API_KEY_EMAIL = "email"
const val API_KEY_MOBILE = "mobile"
const val API_KEY_GENDER = "gender"
const val API_KEY_PASSWORD = "password"
const val API_KEY_USER_TYPE = "user_type"


const val EMPTY_DATA =""
const val ALL_DATA ="getAllData"
const val SINGLE_DATA ="getSingleData"
const val API_KE_METHOD = "method"
const val API_KEY_METHOD = "method"
const val API_GET_TITLE = "title"
const val API_KEY_TITLE = "title"
const val API_KEY_SHORT_DESCRIPTION = "short_description"
const val API_KEY_DESCRIPTION = "description"
const val API_ALL_TAG = "alt_tag"
const val API_KEY_FORMATE_TYPE = "format_type"
const val API_KEY_SRC_URL = "src_url"
const val API_KEY_ATTEMP_QUESTIONS_LIST = "attempQuestionsList"
const val API_KEY_ATTEMPT_ID = "attempt_id"
const val API_KEY_LENGTH = "length"
const val API_KEY_SIZE = "size"
const val API_KEY_REPEATS = "repeats"
const val API_KEY_SCHEDULE_TYPE = "schedule_type"
const val API_KEY_CLASS_TYPE = "class_type"
const val API_KEY_SCHEDULE_DATE = "schedule_date"
const val API_KEY_SCHEDULE_TIME = "schedule_time"
const val API_KEY_LIMIT = "limit"
const val API_KEY_PAGE = "page"
const val API_KEY_TRANSACTION_ID = "transactionId"
const val API_KEY_SUBJECT_ARRAY = "subject_arr"


const val SAVE_TEST_ATTEMPT_DATA = "saveTestAttemptData"
const val GET_ALL_DATA = "getAllData"
const val TEST_RESULT_DATA = "testResultData"

const val POST_DATA = "post"
const val UPLOAD = "upload"
const val YT_VIDEO = "YT_VDO"
const val FT_PDF = "PDF"
const val FT_DOC = "DOC"
const val FT_IMG = "IMG"
const val TYPE_IMAGE = "IMG"
const val TYPE_STUDENT = "Student"
const val TYPE_TEACHER = "Teacher"
const val TYPE_TEXT = "TXT"
const val VIDEO_TYPE_YT_VDO = "YT_VDO"
const val VIDEO_TYPE_VM_VDO = "VM_VDO"

const val QUESTION_TYPE_MCQ = "mcq"
const val QUESTION_TYPE_MSQ = "msq"
const val QUESTION_TYPE_NT = "nt"

const val KEY_WINDOW = "window"
const val KEY_POSITION = "position"
const val KEY_AUTO_PLAY = "auto_play"
const val KEY_TRACK_SELECTOR_PARAMETERS = "track_selector_parameters"

const val NOTIFICATION_TYPE_KEY_DOUBT = "doubt"
const val NOTIFICATION_TYPE_KEY_VIDEO = "video"
const val NOTIFICATION_TYPE_KEY_NOTE = "note"
const val NOTIFICATION_TYPE_KEY_LIVE_CLASS = "live_class"
